# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'javi_mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for javi_mobile

  # Chart UIs
  pod 'Charts'

  # Data
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'RealmSwift'
  
  pod 'MBProgressHUD', '~> 1.1'
  pod 'TPKeyboardAvoiding', '~> 1.3'
end
